### ISSUE TITLE
map-component.component.html:3: Add source of coordinates.

### ISSUE THREAD

**Issue by 0pdd** [SergeyShapovaIov/CityEquipping#12]
The puzzle `2-d77d1bc9` from #2 has to be resolved: 

https://github.com/SergeyShapovaIov/CityEquipping/blob/0e8143b73311ff56c07a80c1d8c16a8b1d609965/src/app/components/map-component/map-component.component.html#L3-L3

The puzzle was created by @SergeyShapovaIov on 15-Jan-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by ssh4rd** [comment]
The coordinates were added in another issue  (#1)
