### ISSUE TITLE
Create map component

### ISSUE THREAD

**Issue by ssh4rd** [SergeyShapovaIov/CityEquipping#2]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/86362529/212501081-0432c5bc-4075-4c67-be38-dd59370fc235.png">

**Comment by SergeyShapovaIov** [comment]
`



<!DOCTYPE html>
    <html>
        <head>
            <title>Right City</title>

            <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=b2832005-a1cc-47d0-a9eb-84c9d8e80205" type="text/javascript"></script>

            <style>
                html, body, #map {
                    width: 100%; height: 100%; padding: 0; margin: 0;
                }
            </style>

            <script>
                ymaps.ready(init);

                function init() {
                    // Создаем карту.
                    var myMap = new ymaps.Map("map", {
                        center: [48.7194, 44.5018],
                        zoom: 12
                    }, {
                        searchControlProvider: 'yandex#search'
                    });

                    // Создаем круги
                    var coordinatesList =${_coordinatesList};
                    createCircle();
                    function createCircle(){
                        for (var i = 0; i < coordinatesList.length; i++){

                            var myCircle = new ymaps.Circle([coordinatesList[i],100],
                                {
                                    balloonContent: "Радиус круга - 10 км",
                                    hintContent: "Подвинь меня"
                                },
                                {
                                    draggable: false,
                                    fillColor: "#DB709377",
                                    strokeColor: "#990066",
                                    strokeOpacity: 0.8,
                                    strokeWidth: 5
                                });
                            myMap.geoObjects.add(myCircle);
                        }
                    };
                }

            </script>
        </head>
        <body>
            <div id="map"></div>
            <div class="menu">
                <input>
            </div>
            <style>

                body
                {
                    padding: 0;
                    margin: 0;
                }
                #map
                {
                    margin: 0;
                    padding: 0;
                    width: 70%;
                    height: 100vh;
                    float: right;

                }
                .menu
                {
                    position: fixed;
                    top: 0;
                    left: 0;
                    margin: 20px;
                    height: 90%;
                    width: 28%;

                    background-color: cadetblue;
                }
            </style>
        </body>
    </html>
`

**Comment by ssh4rd** [comment]
https://yandex.ru/dev/maps/jsapi/doc/2.1/quick-start/index.html?from=techmapsmain

**Comment by ssh4rd** [comment]
b2832005-a1cc-47d0-a9eb-84c9d8e80205

This is API key

**Comment by l3r8yJ** [comment]
@SergeyShapovaIov  from which source I get the coordinates of the points?

**Comment by ssh4rd** [comment]
@l3r8yJ There is no definite decision on this issue yet. At the moment we are considering two sources OpenStreetMap and Yandex maps. Try to get more information on these sources and make a choice

**Comment by 0pdd** [comment]
@SergeyShapovaIov the puzzle [#12](https://github.com/SergeyShapovaIov/CityEquipping/issues/12) is still not solved.
